### Obtener todas
GET http://localhost:2007/sucursales

### Crear Sucursal
POST http://localhost:2007/sucursales
Content-Type: application/json

{
  "nombre": "Sucursal Centro",
  "direccion": "Av. Principal 123",
  "horarioAtencion": "09:00 - 19:00",
  "personalAsignado": "Juan (Jefe), Ana (Vendedora)",
  "politicas": "Uso obligatorio de uniforme"
}