#### obtener todas las devoluciones #####
GET http://gestion-devolucion.us-west-2.elasticbeanstalk.com/devolucion HTTP/1.1
Content-Type: application/json

### obtener devolucion por id #####
GET http://gestion-devolucion.us-west-2.elasticbeanstalk.com/devolucion/1 HTTP/1.1
Content-Type: application/json

#### crear una devolucion #####
POST http://gestion-devolucion.us-west-2.elasticbeanstalk.com/devolucion HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 1,
    "id_cliente": 1,
    "id_venta": 1,
    "motivo_devolucion": "Producto equivocado",
    "fecha_devolucion": "2024-06-15",
    "monto_reembolsado": 20000,
    "estado_venta": "Pendiente"
}

#### actualizar una devolucion #####
PUT http://gestion-devolucion.us-west-2.elasticbeanstalk.com/devolucion HTTP/1.1
Content-Type: application/json

{
    "id_devolucion": 1,
    "id_usuario": 1,
    "id_cliente": 1,
    "id_venta": 1,
    "motivo_devolucion": "Producto dañado",
    "fecha_devolucion": "2024-06-16",
    "monto_reembolsado": 25000,
    "estado_venta": "devolucion completada"
}

