#### hacer reclamo ####
POST http://gestion-reclamo.us-east-1.elasticbeanstalk.com/reclamo HTTP/1.1
Content-Type: application/json

{
    "descripcion_reclamo": "El producto llegó dañado.",
    "fecha_reclamo": "2024-06-14"
}

#### eliminar reclamo ####
DELETE http://gestion-reclamo.us-east-1.elasticbeanstalk.com/reclamo/1 HTTP/1.1
Content-Type: application/json

#### obtener reclamo por id ####
GET http://gestion-reclamo.us-east-1.elasticbeanstalk.com/reclamo/1 HTTP/1.1
Content-Type: application/json

#### ver todos los reclamos ####
GET http://gestion-reclamo.us-east-1.elasticbeanstalk.com/reclamo HTTP/1.1
Content-Type: application/json