###### 1. Hacer un envio a la bodega
POST http://localhost:2013/envios HTTP/1.1
Content-Type: application/json

{
    "origen": "Bodega Principal",
    "idSucursalDestino": 1,
    "descripcion": "Caja de perfumes 50 unidades"
}




### 3. Ver todos los envíos
GET http://localhost:2013/envios HTTP/1.1


### 4. Cambiar estado a EN_CAMINO
PUT http://localhost:2013/envios/1/estado?estado=EN_CAMINO HTTP/1.1