### 1. Obtener todos los productos del inventario
GET http://localhost:2027/inventario HTTP/1.1
Content-Type: application/json

###

### 2. Agregar un nuevo producto (POST)
POST http://localhost:2027/inventario HTTP/1.1
Content-Type: application/json

{
    "nombre": "Polo Blue",
    "genero": "Hombre",
    "precio": 70000,
    "stock": 20
}

###

### 3. Actualizar datos de un producto (PUT)
# Usamos la ID 1 (suponiendo que ya creaste uno)
PUT http://localhost:2024/pfl_inventario/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Polo Blue EDP",
    "genero": "Hombre",
    "precio": 75000,
    "stock": 20
}


### 5. Eliminar un producto (DELETE)
DELETE http://localhost:2024/pfl_inventario/1 HTTP/1.1
Content-Type: application/json

###

### 6. Obtener producto por ID
GET http://localhost:2024/pfl_inventario/1 HTTP/1.1
Content-Type: application/json